# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS builder
WORKDIR /app
COPY package*.json tsconfig.json ./
RUN npm install --ignore-scripts
COPY src ./src
RUN npm run build

FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/build ./build
COPY package*.json ./
# Only needed for prod dependencies (none here except sdk)
RUN npm install --production --ignore-scripts
# Create output dir
RUN mkdir -p ./output
ENV NODE_ENV=production
ENTRYPOINT ["node", "build/index.js"]
